// Generated by gencpp from file proj2_pkg/BicycleCommandMsg.msg
// DO NOT EDIT!


#ifndef PROJ2_PKG_MESSAGE_BICYCLECOMMANDMSG_H
#define PROJ2_PKG_MESSAGE_BICYCLECOMMANDMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proj2_pkg
{
template <class ContainerAllocator>
struct BicycleCommandMsg_
{
  typedef BicycleCommandMsg_<ContainerAllocator> Type;

  BicycleCommandMsg_()
    : linear_velocity(0.0)
    , steering_rate(0.0)  {
    }
  BicycleCommandMsg_(const ContainerAllocator& _alloc)
    : linear_velocity(0.0)
    , steering_rate(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _steering_rate_type;
  _steering_rate_type steering_rate;





  typedef boost::shared_ptr< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> const> ConstPtr;

}; // struct BicycleCommandMsg_

typedef ::proj2_pkg::BicycleCommandMsg_<std::allocator<void> > BicycleCommandMsg;

typedef boost::shared_ptr< ::proj2_pkg::BicycleCommandMsg > BicycleCommandMsgPtr;
typedef boost::shared_ptr< ::proj2_pkg::BicycleCommandMsg const> BicycleCommandMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator1> & lhs, const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator2> & rhs)
{
  return lhs.linear_velocity == rhs.linear_velocity &&
    lhs.steering_rate == rhs.steering_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator1> & lhs, const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proj2_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98601f97a39c5d728d155ceb909428fe";
  }

  static const char* value(const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98601f97a39c5d72ULL;
  static const uint64_t static_value2 = 0x8d155ceb909428feULL;
};

template<class ContainerAllocator>
struct DataType< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proj2_pkg/BicycleCommandMsg";
  }

  static const char* value(const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The commands to a bicycle model robot (v, phi)\n"
"float64 linear_velocity\n"
"float64 steering_rate\n"
;
  }

  static const char* value(const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_velocity);
      stream.next(m.steering_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BicycleCommandMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proj2_pkg::BicycleCommandMsg_<ContainerAllocator>& v)
  {
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "steering_rate: ";
    Printer<double>::stream(s, indent + "  ", v.steering_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJ2_PKG_MESSAGE_BICYCLECOMMANDMSG_H
